version: "3.7"

services:
    roscore:
        image: osrf/ros:kinetic-desktop-full
        command: roscore

    rosbridge:
        build: .
        image: naosharp
        command: /start_after_rosmaster.sh roslaunch file_server ros_sharp_communication.launch
        ports:
            - "9090:9090"
        depends_on:
            - roscore

    nao_description:
        build: .
        image: naosharp
        command: /start_after_rosmaster.sh roslaunch nao_description robot_state_publisher.launch
        depends_on:
            - roscore

    naosharp:
        build: .
        image: naosharp
        volumes:
            - ./naosharp:/catkin_ws/src/naosharp
        command: /start_after_rosmaster.sh rosrun naosharp scripts/nao_arm_mover.py
        depends_on:
            - roscore
